export const NOMEC_ALTERADO = 'NOMEC_ALTERADO'
export const TIPOC_ALTERADO = 'TIPOC_ALTERADO'
export const REFEICAOC_ALTERADO = 'REFEICAOC_ALTERADO'
export const DESCRICAOC_ALTERADO = 'DESCRICAOC_ALTERADO'
export const PRECOC_ALTERADO = 'PRECOC_ALTERADO'

export const NOMER_ALTERADO = 'NOMER_ALTERADO'
export const TIPOR_ALTERADO = 'TIPOR_ALTERADO'